[tool.briefcase]
project_name = "Bee Swift"
bundle = "com.example"
version = "0.0.1"
url = "https://example.com/beeswift"
license = "BSD license"
author = 'Jane Developer'
author_email = "jane@example.com"

[tool.briefcase.app.beeswift]
formal_name = "Bee Swift"
description = "Add Python to a SwiftUI application with the BeeWare Briefcase"
icon = "src/beeswift/resources/beeswift"
sources = ['src/beeswift']
requires = [
]


[tool.briefcase.app.beeswift.macOS]
requires = [
    'toga-cocoa>=0.3.0.dev34',
    'std-nslog~=1.0.0'
]

[tool.briefcase.app.beeswift.linux]
requires = [
    'toga-gtk>=0.3.0.dev34',
]

[tool.briefcase.app.beeswift.linux.appimage]
system_requires = [
    'gir1.2-webkit-3.0',
    'libcairo2-dev',
    'libgirepository1.0-dev',
    'libgtk-3-dev',
    'libpango1.0-dev',
    'librsvg2-dev',
    'libwebkitgtk-3.0-0',
]
linuxdeploy_plugins = [
    'DEPLOY_GTK_VERSION=3 gtk',
]

[tool.briefcase.app.beeswift.linux.flatpak]
flatpak_runtime = 'org.gnome.Platform'
flatpak_runtime_version = '42'
flatpak_sdk = 'org.gnome.Sdk'

[tool.briefcase.app.beeswift.windows]
requires = [
    'toga-winforms>=0.3.0.dev34',
]

# Mobile deployments
[tool.briefcase.app.beeswift.iOS]
requires = [
    'toga-iOS>=0.3.0.dev34',
    'std-nslog~=1.0.0'
]

[tool.briefcase.app.beeswift.android]
requires = [
    'toga-android>=0.3.0.dev34'
]
